spring.application.name: congressman-service
server.port: 8081

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#Database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meet_congress?charSet=UTF8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa.database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  jpa.show-sql: false
  jpa.hibernate.ddl-auto: validate

logging.level.org.hibernate.SQL: debug

#    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#      hibernate.naming.strategy: org.hibernate.cfg.DefaultNamingStrategy