spring.application.name: server-zuul-service
#spring:
#  cloud:
#    config:
#      uri: http://localhost:8888
server.port: 8190

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka.client.service-url.defaultZone: http://localhost:8761/eureka/

zuul.routes.congressman.service-id: congressman-service
zuul.routes.congressman.path: /api/congressman/**
#
#zuul.routes.items.service-id: servicio-items
#zuul.routes.items.path: /api/items/**
#
zuul.routes.users.service-id: user-management-service
zuul.routes.users.path: /api/users/**

zuul.routes.security.service-id: oauth-service
zuul.routes.security.path: /api/security/**
zuul.routes.security.sensitive-headers: Cookie,Set-Cookie


config.security.oauth:
  client:
    id: frontendapp
    secret: 12345
  jwt.key: key

oauth-service:
  ribbon:
    listOfServers: http://localhost:8190/

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
#ribbon.ConnectTimeout: 9000
# ribbon.ReadTimeout: 30000
#
#spring.sleuth.sampler.probability: 1.0
#
#spring.zipkin.sender.type: rabbit
#spring.zipkin.rabbitmq.queue: zipkin
#spring.rabbitmq.addresses: localhost:5672
#spring.rabbitmq.username: guest
#spring.rabbitmq.password: guest


